export const products = [
  { id: '1', name: 'Ореховое печенье', desc: 'Без сахара', price: 79, kcal: 95, protein: 6, fat: 3, carbs: 12, image: require('../assets/products/almondcookie.png') },
  { id: '2', name: 'Яблочные вафли', desc: 'Мало углеводов', price: 85, kcal: 88, protein: 5, fat: 2, carbs: 10, image: require('../assets/products/applewaffle.png') },
  { id: '3', name: 'Банановый батончик', desc: 'Без сахара', price: 69, kcal: 110, protein: 4, fat: 2, carbs: 18, image: require('../assets/products/bananabar.png') },
  { id: '4', name: 'Ягодное печенье', desc: 'С ягодами', price: 75, kcal: 90, protein: 5, fat: 3, carbs: 11, image: require('../assets/products/berrycookie.png') },
  { id: '5', name: 'Ягодные вафли', desc: 'С ягодами', price: 95, kcal: 105, protein: 6, fat: 3, carbs: 15, image: require('../assets/products/berrywaffle.png') },
  { id: '6', name: 'Гречневые вафли', desc: 'Больше клетчатки', price: 82, kcal: 92, protein: 7, fat: 2, carbs: 10, image: require('../assets/products/buckwheatwaffle.png') },
  { id: '7', name: 'Гречневый батончик', desc: 'Для фитнеса', price: 72, kcal: 98, protein: 8, fat: 2, carbs: 9, image: require('../assets/products/buckwheatbar.png') },
  { id: '8', name: 'Кешью батончик', desc: 'Кешью и мед', price: 88, kcal: 130, protein: 5, fat: 6, carbs: 16, image: require('../assets/products/cashewbar.png') },
  { id: '9', name: 'Кокосовое печенье', desc: 'Без глютена', price: 77, kcal: 96, protein: 4, fat: 4, carbs: 12, image: require('../assets/products/coconutcookie.png') },
  { id: '10', name: 'Кокосовый батончик', desc: 'С кокосовой стружкой', price: 84, kcal: 115, protein: 5, fat: 5, carbs: 17, image: require('../assets/products/coconutbar.png') },
  { id: '11', name: 'Финиковый батончик', desc: 'Без сахара', price: 79, kcal: 120, protein: 3, fat: 2, carbs: 22, image: require('../assets/products/datebar.png') },
  { id: '12', name: 'Фруктовый батончик', desc: 'Ассорти фруктов', price: 82, kcal: 118, protein: 4, fat: 2, carbs: 20, image: require('../assets/products/fruitnut.png') },
  { id: '13', name: 'Медовый батончик', desc: 'С мёдом', price: 85, kcal: 122, protein: 4, fat: 3, carbs: 21, image: require('../assets/products/honeybar.png') },
  { id: '14', name: 'Медовое печенье', desc: 'Мёд и орехи', price: 78, kcal: 94, protein: 5, fat: 3, carbs: 12, image: require('../assets/products/honeycookie.png') },
  { id: '15', name: 'Медовое печенье 2', desc: 'Классика', price: 76, kcal: 92, protein: 4, fat: 3, carbs: 11, image: require('../assets/products/honeycookie2.png') },
  { id: '16', name: 'Ореховое печенье 2', desc: 'Орехи и мёд', price: 88, kcal: 98, protein: 6, fat: 4, carbs: 13, image: require('../assets/products/nutcookie.png') },
  { id: '17', name: 'Ореховый батончик', desc: 'С орехами', price: 90, kcal: 125, protein: 6, fat: 6, carbs: 15, image: require('../assets/products/nutbar.png') },
  { id: '18', name: 'Шоколадный батончик', desc: 'Шоколад и орехи', price: 97, kcal: 135, protein: 5, fat: 7, carbs: 18, image: require('../assets/products/nutchocobar.png') },
  { id: '19', name: 'Апельсиновый батончик', desc: 'Апельсин и злаки', price: 80, kcal: 110, protein: 4, fat: 3, carbs: 17, image: require('../assets/products/orangebar.png') },
  { id: '20', name: 'Персиковый батончик', desc: 'Фрукты и орехи', price: 80, kcal: 108, protein: 4, fat: 3, carbs: 16, image: require('../assets/products/peachbar.png') },
  { id: '21', name: 'Чайное печенье', desc: 'К чаю', price: 68, kcal: 85, protein: 3, fat: 2, carbs: 11, image: require('../assets/products/teacookie.png') },
  { id: '22', name: 'Бар №1', desc: 'Специальная серия', price: 92, kcal: 140, protein: 7, fat: 7, carbs: 19, image: require('../assets/products/bar1.png') },
  { id: '23', name: 'Клубничная вафля', desc: 'С клубникой', price: 95, kcal: 112, protein: 5, fat: 4, carbs: 16, image: require('../assets/products/strawberrywaffle.png') },
  { id: '24', name: 'Ореховая вафля', desc: 'Ореховая начинка', price: 92, kcal: 118, protein: 6, fat: 5, carbs: 15, image: require('../assets/products/nutwaffle.png') },
  { id: '25', name: 'Вафля с ягодами', desc: 'Ягодная начинка', price: 88, kcal: 105, protein: 5, fat: 4, carbs: 14, image: require('../assets/products/berrywaffle.png') },
  { id: '26', name: 'Вафля гречневая', desc: 'Гречневая основа', price: 82, kcal: 100, protein: 6, fat: 3, carbs: 12, image: require('../assets/products/waffle1.png') },
  { id: '27', name: 'Шоколадная вафля', desc: 'С шоколадом', price: 95, kcal: 130, protein: 5, fat: 6, carbs: 18, image: require('../assets/products/chocowaffle.png') },
  { id: '28', name: 'Песочное печенье', desc: 'Классическое', price: 65, kcal: 90, protein: 3, fat: 3, carbs: 12, image: require('../assets/products/cookie1.png') },
];
