export const products = [
  { id: '1', name: 'Злаковый батончик', desc: 'Без сахара', description: 'Полезный злаковый батончик идеально подходит для правильного питания. Без добавления сахара и лишних калорий.', kcal: 102, protein: 2.7, fat: 3.5, carbs: 15.6, image: 'https://via.placeholder.com/200' },
  { id: '2', name: 'Вафли', desc: 'С пониженным содержанием углеводов', description: 'Пониженное содержание углеводов и сахара. Вафли, которые можно есть в любое время.', kcal: 120, protein: 8.5, fat: 9.2, carbs: 4.5, image: 'https://via.placeholder.com/200' },
  { id: '3', name: 'Печенье овсяное', desc: 'На фруктозе', description: 'Печенье с фруктозой, идеальное для сладкоежек, следящих за фигурой.', kcal: 97, protein: 1.4, fat: 4.1, carbs: 13.2, image: 'https://via.placeholder.com/200' },
  { id: '4', name: 'Медовые батончики', desc: 'С натуральным медом', description: 'Подробное описание товара', kcal: 120, protein: 3.0, fat: 4.5, carbs: 14.0, image: 'https://via.placeholder.com/200' },
  { id: '5', name: 'Гречневые вафли', desc: 'С высоким содержанием клетчатки', description: 'Подробное описание товара', kcal: 80, protein: 3.5, fat: 2.0, carbs: 10.0, image: 'https://via.placeholder.com/200' },
  { id: '6', name: 'Кокосовое печенье', desc: 'Без глютена', description: 'Подробное описание товара', kcal: 150, protein: 2.0, fat: 8.0, carbs: 14.0, image: 'https://via.placeholder.com/200' },
  { id: '7', name: 'Чайные печенья', desc: 'С добавлением ванили', description: 'Подробное описание товара', kcal: 110, protein: 1.2, fat: 4.2, carbs: 18.5, image: 'https://via.placeholder.com/200' },
  { id: '8', name: 'Овсяные хлопья', desc: 'Для завтраков', description: 'Подробное описание товара', kcal: 90, protein: 5.0, fat: 3.0, carbs: 15.5, image: 'https://via.placeholder.com/200' },
  { id: '9', name: 'Ореховый батончик', desc: 'С медом и орехами', description: 'Подробное описание товара', kcal: 140, protein: 4.0, fat: 8.0, carbs: 16.0, image: 'https://via.placeholder.com/200' },
  { id: '10', name: 'Ягодные вафли', desc: 'С добавлением свежих ягод', description: 'Подробное описание товара', kcal: 130, protein: 5.0, fat: 6.5, carbs: 20.0, image: 'https://via.placeholder.com/200' },
  { id: '11', name: 'Кешью батончик', desc: 'С орехами кешью и медом', description: 'Подробное описание товара', kcal: 180, protein: 6.5, fat: 12.0, carbs: 14.5, image: 'https://via.placeholder.com/200' },
  { id: '12', name: 'Шоколадные вафли', desc: 'С темным шоколадом', description: 'Подробное описание товара', kcal: 200, protein: 3.5, fat: 10.0, carbs: 22.0, image: 'https://via.placeholder.com/200' },
  { id: '13', name: 'Миндальные печенья', desc: 'С миндальным кремом', description: 'Подробное описание товара', kcal: 160, protein: 2.5, fat: 10.0, carbs: 18.0, image: 'https://via.placeholder.com/200' },
  { id: '14', name: 'Апельсиновые батончики', desc: 'С натуральным апельсиновым соком', description: 'Подробное описание товара', kcal: 120, protein: 2.0, fat: 5.5, carbs: 16.5, image: 'https://via.placeholder.com/200' },
  { id: '15', name: 'Клубничные вафли', desc: 'С добавлением клубники', description: 'Подробное описание товара', kcal: 140, protein: 4.0, fat: 6.0, carbs: 18.0, image: 'https://via.placeholder.com/200' },
  { id: '16', name: 'Финиковые батончики', desc: 'С финиками и орехами', description: 'Подробное описание товара', kcal: 150, protein: 3.0, fat: 6.5, carbs: 21.0, image: 'https://via.placeholder.com/200' },
  { id: '17', name: 'Яблочные вафли', desc: 'С добавлением яблок', description: 'Подробное описание товара', kcal: 110, protein: 2.5, fat: 3.0, carbs: 20.0, image: 'https://via.placeholder.com/200' },
  { id: '18', name: 'Гречневые батончики', desc: 'С гречкой и медом', description: 'Подробное описание товара', kcal: 130, protein: 4.5, fat: 5.0, carbs: 18.5, image: 'https://via.placeholder.com/200' },
  { id: '19', name: 'Шоколадные печенья', desc: 'С кусочками шоколада', description: 'Подробное описание товара', kcal: 180, protein: 2.5, fat: 8.0, carbs: 25.0, image: 'https://via.placeholder.com/200' },
  { id: '20', name: 'Печенье с орехами', desc: 'С орехами кешью и фундуком', description: 'Подробное описание товара', kcal: 140, protein: 3.5, fat: 7.5, carbs: 18.0, image: 'https://via.placeholder.com/200' },
  { id: '21', name: 'Ореховые вафли', desc: 'С орехами и медом', description: 'Подробное описание товара', kcal: 160, protein: 4.0, fat: 8.5, carbs: 19.0, image: 'https://via.placeholder.com/200' },
  { id: '22', name: 'Фрукты с орехами', desc: 'Ассорти из сухофруктов и орехов', description: 'Подробное описание товара', kcal: 110, protein: 2.5, fat: 5.0, carbs: 22.0, image: 'https://via.placeholder.com/200' },
  { id: '23', name: 'Медовые печенья', desc: 'С медом и корицей', description: 'Подробное описание товара', kcal: 160, protein: 2.0, fat: 7.0, carbs: 20.0, image: 'https://via.placeholder.com/200' },
  { id: '24', name: 'Батончик с орехами', desc: 'С орехами и шоколадом', description: 'Подробное описание товара', kcal: 190, protein: 5.0, fat: 12.0, carbs: 22.0, image: 'https://via.placeholder.com/200' },
  { id: '25', name: 'Шоколад с орехами', desc: 'Темный шоколад с орехами', description: 'Подробное описание товара', kcal: 210, protein: 3.0, fat: 15.0, carbs: 22.5, image: 'https://via.placeholder.com/200' },
  { id: '26', name: 'Кокосовые батончики', desc: 'С кокосовой стружкой', description: 'Подробное описание товара', kcal: 130, protein: 3.0, fat: 6.0, carbs: 18.0, image: 'https://via.placeholder.com/200' },
  { id: '27', name: 'Персиковые батончики', desc: 'С натуральными персиками', description: 'Подробное описание товара', kcal: 140, protein: 4.5, fat: 7.0, carbs: 20.0, image: 'https://via.placeholder.com/200' },
  { id: '28', name: 'Банановые батончики', desc: 'С добавлением бананов', description: 'Подробное описание товара', kcal: 130, protein: 3.5, fat: 6.0, carbs: 17.5, image: 'https://via.placeholder.com/200' },
  { id: '29', name: 'Печенье с ягодами', desc: 'С черникой и малиной', description: 'Подробное описание товара', kcal: 110, protein: 2.0, fat: 5.5, carbs: 19.0, image: 'https://via.placeholder.com/200' },
  { id: '30', name: 'Печенье с медом', desc: 'С натуральным медом', description: 'Подробное описание товара', kcal: 120, protein: 3.0, fat: 6.0, carbs: 18.0, image: 'https://via.placeholder.com/200' },
];
