export const products = [
  {
    id: '100',
    name: 'Крекер с кокос',
    desc: 'Без глютена',
    price: 63,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '101',
    name: 'Маршмеллоу с финик',
    desc: 'С начинкой',
    price: 106,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '102',
    name: 'Пастила яблочная с клубника',
    desc: 'С пониженной калорийностью',
    price: 93,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '103',
    name: 'Шоколадка с яблоко',
    desc: 'С начинкой',
    price: 70,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '104',
    name: 'Вафля с яблоко',
    desc: 'С витаминами',
    price: 110,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '105',
    name: 'Пастила с клубника',
    desc: 'С начинкой',
    price: 86,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '106',
    name: 'Батончик с шоколад',
    desc: 'С начинкой',
    price: 102,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '107',
    name: 'Ореховая смесь с финик',
    desc: 'С пониженной калорийностью',
    price: 106,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '108',
    name: 'Фруктовая плитка с клубника',
    desc: 'Классика вкуса',
    price: 67,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '109',
    name: 'Фитнес батончик с шоколад',
    desc: 'Классика вкуса',
    price: 75,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '110',
    name: 'Ореховая смесь с шоколад',
    desc: 'Для спорта',
    price: 74,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '111',
    name: 'Фруктовая плитка с банан',
    desc: 'С пониженной калорийностью',
    price: 108,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '112',
    name: 'Мармелад с апельсин',
    desc: 'Без сахара',
    price: 68,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '113',
    name: 'Трюфель с яблоко',
    desc: 'С пониженной калорийностью',
    price: 108,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '114',
    name: 'Фитнес батончик с кокос',
    desc: 'С витаминами',
    price: 71,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '115',
    name: 'Печенье с клубника',
    desc: 'Для спорта',
    price: 104,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '116',
    name: 'Мармелад с ягоды',
    desc: 'С витаминами',
    price: 72,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '117',
    name: 'Ореховая смесь с шоколад',
    desc: 'Фруктовое наслаждение',
    price: 77,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '118',
    name: 'Крекер с ягоды',
    desc: 'Без глютена',
    price: 110,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '119',
    name: 'Кокосовая плитка с кокос',
    desc: 'С орехами',
    price: 107,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '120',
    name: 'Пастила яблочная с кокос',
    desc: 'С витаминами',
    price: 114,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '121',
    name: 'Батончик с орех',
    desc: 'Классика вкуса',
    price: 99,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '122',
    name: 'Шоколадка с кокос',
    desc: 'Для спорта',
    price: 117,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '123',
    name: 'Фруктовая плитка с яблоко',
    desc: 'С пониженной калорийностью',
    price: 77,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '124',
    name: 'Трюфель с банан',
    desc: 'С пониженной калорийностью',
    price: 85,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '125',
    name: 'Батончик с кокос',
    desc: 'Фруктовое наслаждение',
    price: 65,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '126',
    name: 'Пастила яблочная с кокос',
    desc: 'Без глютена',
    price: 112,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '127',
    name: 'Пастила яблочная с мед',
    desc: 'Без сахара',
    price: 98,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '128',
    name: 'Кокосовая плитка с яблоко',
    desc: 'С витаминами',
    price: 73,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '129',
    name: 'Маршмеллоу с ягоды',
    desc: 'Для спорта',
    price: 91,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '130',
    name: 'Печенье овсяное с финик',
    desc: 'С начинкой',
    price: 111,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '131',
    name: 'Пастила яблочная с шоколад',
    desc: 'С витаминами',
    price: 61,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '132',
    name: 'Пастила с яблоко',
    desc: 'Классика вкуса',
    price: 82,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '133',
    name: 'Пастила с орех',
    desc: 'Для спорта',
    price: 81,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '134',
    name: 'Фитнес батончик с апельсин',
    desc: 'Классика вкуса',
    price: 64,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '135',
    name: 'Батончик с яблоко',
    desc: 'Без сахара',
    price: 119,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '136',
    name: 'Трюфель с мед',
    desc: 'Для спорта',
    price: 118,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '137',
    name: 'Кокосовая плитка с клубника',
    desc: 'С витаминами',
    price: 79,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '138',
    name: 'Вафля с ягоды',
    desc: 'С орехами',
    price: 116,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '139',
    name: 'Печенье овсяное с яблоко',
    desc: 'С пониженной калорийностью',
    price: 60,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '140',
    name: 'Ореховая смесь с орех',
    desc: 'Для спорта',
    price: 106,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '141',
    name: 'Вафля с клубника',
    desc: 'С витаминами',
    price: 112,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '142',
    name: 'Маршмеллоу с орех',
    desc: 'С начинкой',
    price: 110,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '143',
    name: 'Шоколадка с апельсин',
    desc: 'Фруктовое наслаждение',
    price: 120,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '144',
    name: 'Ореховая смесь с мед',
    desc: 'С орехами',
    price: 110,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '145',
    name: 'Фруктовая плитка с ягоды',
    desc: 'С пониженной калорийностью',
    price: 86,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '146',
    name: 'Крекер с шоколад',
    desc: 'С пониженной калорийностью',
    price: 113,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '147',
    name: 'Пастила яблочная с банан',
    desc: 'Без сахара',
    price: 102,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '148',
    name: 'Мармелад с клубника',
    desc: 'С начинкой',
    price: 60,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '149',
    name: 'Крекер с яблоко',
    desc: 'Классика вкуса',
    price: 102,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '150',
    name: 'Трюфель с мед',
    desc: 'Без сахара',
    price: 81,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '151',
    name: 'Пастила с кокос',
    desc: 'Без глютена',
    price: 74,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '152',
    name: 'Печенье с клубника',
    desc: 'Фруктовое наслаждение',
    price: 109,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '153',
    name: 'Мармелад с ягоды',
    desc: 'С орехами',
    price: 92,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '154',
    name: 'Фруктовая плитка с мед',
    desc: 'С начинкой',
    price: 112,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '155',
    name: 'Фитнес батончик с яблоко',
    desc: 'Фруктовое наслаждение',
    price: 69,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '156',
    name: 'Мармелад с апельсин',
    desc: 'Для спорта',
    price: 120,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '157',
    name: 'Мармелад с банан',
    desc: 'Без сахара',
    price: 87,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '158',
    name: 'Вафля с мед',
    desc: 'Классика вкуса',
    price: 96,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '159',
    name: 'Вафля с апельсин',
    desc: 'Без сахара',
    price: 98,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '160',
    name: 'Фитнес батончик с банан',
    desc: 'С витаминами',
    price: 105,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '161',
    name: 'Печенье овсяное с ягоды',
    desc: 'С орехами',
    price: 100,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '162',
    name: 'Батончик с апельсин',
    desc: 'С пониженной калорийностью',
    price: 105,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '163',
    name: 'Мармелад с ягоды',
    desc: 'Классика вкуса',
    price: 96,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '164',
    name: 'Шоколадка с мед',
    desc: 'С витаминами',
    price: 93,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '165',
    name: 'Шоколадка с ягоды',
    desc: 'Без глютена',
    price: 70,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '166',
    name: 'Фруктовая плитка с банан',
    desc: 'Без глютена',
    price: 117,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '167',
    name: 'Кокосовая плитка с мед',
    desc: 'С орехами',
    price: 74,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '168',
    name: 'Ореховая смесь с яблоко',
    desc: 'С витаминами',
    price: 78,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '169',
    name: 'Пастила с кокос',
    desc: 'С пониженной калорийностью',
    price: 97,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '170',
    name: 'Кокосовая плитка с яблоко',
    desc: 'Без сахара',
    price: 120,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '171',
    name: 'Вафля с банан',
    desc: 'Без глютена',
    price: 97,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '172',
    name: 'Трюфель с банан',
    desc: 'С начинкой',
    price: 118,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '173',
    name: 'Мармелад с мед',
    desc: 'С витаминами',
    price: 100,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '174',
    name: 'Вафля с мед',
    desc: 'С орехами',
    price: 116,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '175',
    name: 'Пастила яблочная с орех',
    desc: 'С витаминами',
    price: 99,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '176',
    name: 'Маршмеллоу с орех',
    desc: 'С витаминами',
    price: 78,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '177',
    name: 'Трюфель с апельсин',
    desc: 'С витаминами',
    price: 72,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '178',
    name: 'Батончик с ягоды',
    desc: 'С витаминами',
    price: 91,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '179',
    name: 'Вафля с финик',
    desc: 'С пониженной калорийностью',
    price: 81,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '180',
    name: 'Печенье овсяное с шоколад',
    desc: 'Без сахара',
    price: 114,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '181',
    name: 'Батончик с банан',
    desc: 'Для спорта',
    price: 117,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '182',
    name: 'Шоколадка с апельсин',
    desc: 'С витаминами',
    price: 90,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '183',
    name: 'Вафля с банан',
    desc: 'Без сахара',
    price: 77,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '184',
    name: 'Печенье с шоколад',
    desc: 'С витаминами',
    price: 71,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '185',
    name: 'Трюфель с орех',
    desc: 'Для спорта',
    price: 96,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '186',
    name: 'Маршмеллоу с мед',
    desc: 'Классика вкуса',
    price: 66,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '187',
    name: 'Пастила с орех',
    desc: 'Без глютена',
    price: 104,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '188',
    name: 'Маршмеллоу с орех',
    desc: 'Классика вкуса',
    price: 65,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '189',
    name: 'Фитнес батончик с апельсин',
    desc: 'С начинкой',
    price: 94,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '190',
    name: 'Пастила яблочная с апельсин',
    desc: 'Фруктовое наслаждение',
    price: 75,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '191',
    name: 'Печенье овсяное с шоколад',
    desc: 'Классика вкуса',
    price: 86,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '192',
    name: 'Фитнес батончик с яблоко',
    desc: 'С витаминами',
    price: 68,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
    isPopular: true,
  },
  {
    id: '193',
    name: 'Кокосовая плитка с банан',
    desc: 'Классика вкуса',
    price: 106,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '194',
    name: 'Мармелад с кокос',
    desc: 'Без глютена',
    price: 94,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '195',
    name: 'Трюфель с шоколад',
    desc: 'Классика вкуса',
    price: 64,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '196',
    name: 'Фитнес батончик с финик',
    desc: 'Классика вкуса',
    price: 69,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
  {
    id: '197',
    name: 'Печенье с яблоко',
    desc: 'Классика вкуса',
    price: 74,
    image: require('../assets/products/placeholder.png'),
    isNew: true,
  },
  {
    id: '198',
    name: 'Шоколадка с клубника',
    desc: 'Фруктовое наслаждение',
    price: 106,
    image: require('../assets/products/placeholder.png'),
  },
  {
    id: '199',
    name: 'Трюфель с апельсин',
    desc: 'С пониженной калорийностью',
    price: 104,
    image: require('../assets/products/placeholder.png'),
    isPopular: true,
  },
];